### ISSUE TITLE
keep track of what user entered in the "create task" form, and re-fill it upon display

### ISSUE THREAD

**Issue by violet4** [mica5/clarify#13]
keep the new task register updated whenever user enters input into the "create new task" form. then, inside the view that shows the "create task" form, pass in the new task register, and pre-populate the "create task" form with the values from the "new task register" object.

**Comment by grivoire1** [comment]
I wasn't able to figure out how to input the progress of a life goal back into the textbox, like the original plan was, so it prints the word just above the box and saves whatever was written last. You can copy and paste the saved word if need be or retype it into the input box

**Comment by violet4** [comment]
thanks @grivoire1 , I'll look into it.

**Comment by violet4** [comment]
this is obsoleted by #32
