### ISSUE TITLE
Scope Changes

### ISSUE THREAD

**Issue by Hovspian** [mica5/clarify#4]
Scope as discussed on 4/21
Goal is to make the project smaller and more feasible by the deadline. Will re-add features if time permits.

- Have three views on main page: today (selects a prioritized set of tasks), tasks (all tasks, ordered by priority, possibly add option to also group by life goal), life goals
- Tasks: have a description, are categorized under a life goal, assigned a priority, and (optionally?) an estimated time to complete
- Tasks are singular: we are not creating recursive subtasks
- Life goals: Only have a description
- Model contains life goals, all tasks, and today/focus

**Comment by violet4** [comment]
it appears that all that remains on this tickete is to clean up the model type, to remove fields that are unused. however, that might break the app for users who have data saved... we don't need to delete those things, so we could just close this ticket.
